language: java
jdk:
  - openjdk6

before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
  - tar -zxvf android-sdk_r22.0.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools
  - android list sdk
  - echo "y" | android -v update sdk --filter 1,2,4,5,6 --no-ui
  - export PATH=${PATH}:${ANDROID_HOME}/platform-tools
  - android list targets
  - android -s update project --path ./smssync --subprojects --target "android-17"
  - android -s update test-project --path ./smssync/tests -m ../
  - ln -s android-sdk-linux/build-tools/17.0.0/aapt android-sdk-linux/platform-tools/aapt
  - ln -s android-sdk-linux/build-tools/17.0.0/lib android-sdk-linux/platform-tools/lib
  - ln -s android-sdk-linux/build-tools/17.0.0/aidl android-sdk-linux/platform-tools/aidl



script: "./build.sh"

notifications:
  email:
   -henry@ushahidi.com

